#!/bin/bash

#  Copyright 2021 Canonical Ltd.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ ! -z "${VIRTUAL_ENV}" ]; then
    pip install --upgrade -r requirements-dev.txt > /dev/null
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="lib:src"
else
    export PYTHONPATH="lib:src:$PYTHONPATH"
fi

flake8 || exit $?
if [ "$1" == '--fix' ]; then
    black src tests
    shift
else
    black --diff --check src tests || exit $?
fi
which pytest > /dev/null
if [ $? -eq 0 ]; then
    coverage run --source=src,lib -m pytest -v "$@"
else
    coverage run --source=src,lib -m unittest -v "$@"
fi
coverage report -m
